### ISSUE TITLE
minor bug

### ISSUE THREAD

**Issue by ddaydd** [pantreeco/meteor-zendesk#1]
hello,

first
missing coma in settings.json exemple after "username": "<Your Zendesk username>"

second
zendesk is not defined but Zendesk is Function

Edit:
ok it's work when i add
var zendesk = Zendesk();
it's the right way?

Sorry for my poor english...

**Comment by jchittick** [comment]
Hi dyddad,

Good pickup in the settings example!

Correct the usage is

```
var zendesk = Zendesk();
```

A recent change in the Zendesk API requires requesters to have a locale_id too.

```
var requester = {
    locale_id: 1,
    name: 'test user',
    email: 'user@testmeteorzendesk.com'
};
```

**Comment by garynakanelua** [comment]
@jchittick : Following the conversation above, should a typical request (such as getting a ticket list) go as `zendesk.tickets.list(err&res stuff here)`

**Comment by jchittick** [comment]
Hi @garynakanelua , yes the following works.

```
zendesk.tickets.list(function(err, req, res) {
    if (err) {
        console.log(err);
        return;
    }
    console.log(req);
    console.log(res);
});
```

**Comment by ycpatel813** [comment]
Hi 
I did not understand where i have to use var zendesk = Zendesk() and how to import zendesk.

Thanks.

**Comment by ddaydd** [comment]
Hi ycpatel813,

I do not understand what you do not understand

import zendesk to your project with 
meteor add pantreeco:zendesk

**Comment by ycpatel813** [comment]
@ddaydd  I have add zendesk using meteor add pantreeco:zendesk.
and import using `import {zendesk} from 'meteor/pantreeco:zendesk'`

but when I console.log(zendesk) is null object.
I want to create user so need client
 
var client = zendesk.createClient({
  username:  'username',
  token:     'token',
  remoteUri: 'https://remote.zendesk.com/api/v2'
});

but zendesk is null object so I can not create client.
May be you get my point. 
Thank you.

**Comment by ddaydd** [comment]
And with 
`import {Zendesk} from 'meteor/pantreeco:zendesk'`
`var zendesk = Zendesk();`

**Comment by ycpatel813** [comment]
I followed this steps
but after I print zendesk using console.log.
![2017-05-09_1535](https://cloud.githubusercontent.com/assets/8921044/25845854/2b67ee98-34cd-11e7-85c6-06f8404c1183.png)

Thank you.

**Comment by ddaydd** [comment]
sorry, i can't test now,

but can you `console.log(Zendesk)` after import?

**Comment by ycpatel813** [comment]
console.log(Zendesk) and undefined.
Totally confuse what going on.

**Comment by ddaydd** [comment]
is your import {Zendesk} ... with a capital letter? Zendesk , not zendesk

**Comment by ycpatel813** [comment]
yes @ddaydd I have use 
`import {Zendesk} from 'meteor/pantreeco:zendesk'`
`var zendesk = Zendesk();`

**Comment by ddaydd** [comment]
btw, i don't know why you need `import {Zendesk} from 'meteor/pantreeco:zendesk'`
Zendesk is not named export.
test with this removed line...

**Comment by ycpatel813** [comment]
First, I try with this but give me error Zendesk is not defined.
![2017-05-09_1535](https://cloud.githubusercontent.com/assets/8921044/25847017/e9f17f42-34d1-11e7-9c63-49fb1e4c1822.png)

**Comment by ycpatel813** [comment]
First, I try because I did not find export so but got error
![2017-05-09_1609](https://cloud.githubusercontent.com/assets/8921044/25847047/0c60b5f2-34d2-11e7-8b1b-383d45ff372e.png)
